### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Jakub41** [KaiserCoder/RaveFramework#2]
Hi,
I'm new to MVC can you explain how I can use your system to create more pages? 
I try to create a controller and a new view but when I try to see another page instead of the main I received an error of page doesn't found. I just would like to know this for create a navigation bar.
Thanks for help

**Comment by KaiserCoder** [comment]
Ok,
Thanks for using my Framework :)

It's pretty easy to use. The URL is format as www.yourwebsite/controller/method/{optionnalparams}. If the url is empty, the Framework loads www.yourwebsite/main/index by default. If you only precise the controller name, it will load www.yourwebsite/yourcontroller/index.

Every controller must extends of Rave\Core\Controller. For example:

<?php

use Rave\Core\Controller;

class Mycontroller extends Controller
{
    public function __construct() {
        $this->setLayout('layoutName');
    }

```
public function index() {
    $this->loadView('viewName');
    /* all the code you want*/
}
```

}

If you call www.yourwebsite/mycontroller or www.yourwebsite/mycontroller/index, it will display the view viewName.php inside your layout layoutName.php. The view must be in the directory Application/View/ControllerName and the layout in the directory Application/View/Layout.

If you want a working link, put <a href="/mycontroller/method">Link</a> inside your view.
For the moment, the Framework is only in Alpha version but soon, we will add a nice documentation and a lot more feature.

I hope it will help you :)

**Comment by Jakub41** [comment]
Il 23/04/15 09:52, KaiserCoder ha scritto:

> Ok,
> Thanks for using my Framework :)
> 
> It's pretty easy to use. The URL is format as 
> www.yourwebsite/controller/method/{optionnalparams} 
> http://www.yourwebsite/controller/method/%7Boptionnalparams%7D. If 
> the url is empty, the Framework loads www.yourwebsite/main/index 
> http://www.yourwebsite/main/index by default. If you only precise 
> the controller name, it will load www.yourwebsite/yourcontroller/index 
> http://www.yourwebsite/yourcontroller/index.
> 
> Every controller must extends of Rave\Core\Controller. For example:
> 
> <?php
> 
> use Rave\Core\Controller;
> 
> class Mycontroller extends Controller
> {
> public function __construct() {
> $this->setLayout('layoutName');
> }
> 
> |public function index() {
>      $this->loadView('viewName');
>      /\* all the code you want*/
> }
> |
> 
> }
> 
> If you call www.yourwebsite/mycontroller 
> http://www.yourwebsite/mycontroller or 
> www.yourwebsite/mycontroller/index 
> http://www.yourwebsite/mycontroller/index, it will display the view 
> viewName.php inside your layout layoutName.php. The view must be in 
> the directory Application/View/ControllerName and the layout in the 
> directory Application/View/Layout.
> 
> If you want a working link, put Link </mycontroller/method> inside 
> your view.
> For the moment, the Framework is only in Alpha version but soon, we 
> will add a nice documentation and a lot more feature.
> 
> I hope it will help you :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/KaiserCoder/RaveFramework/issues/2#issuecomment-95480023.
> 
> Hi,
> Thank for the explanation was really good and your framework seems will 
> be a good one.
> I'll try your suggestion.
> Just a last question if I put the views in different folders I have to 
> change in the controller the path to the view?

Thank you :-)

**Comment by Jakub41** [comment]
Il 23/04/15 09:52, KaiserCoder ha scritto:

> Ok,
> Thanks for using my Framework :)
> 
> It's pretty easy to use. The URL is format as 
> www.yourwebsite/controller/method/{optionnalparams} 
> http://www.yourwebsite/controller/method/%7Boptionnalparams%7D. If 
> the url is empty, the Framework loads www.yourwebsite/main/index 
> http://www.yourwebsite/main/index by default. If you only precise 
> the controller name, it will load www.yourwebsite/yourcontroller/index 
> http://www.yourwebsite/yourcontroller/index.
> 
> Every controller must extends of Rave\Core\Controller. For example:
> 
> <?php
> 
> use Rave\Core\Controller;
> 
> class Mycontroller extends Controller
> {
> public function __construct() {
> $this->setLayout('layoutName');
> }
> 
> |public function index() {
>      $this->loadView('viewName');
>      /\* all the code you want*/
> }
> |
> 
> }
> 
> If you call www.yourwebsite/mycontroller 
> http://www.yourwebsite/mycontroller or 
> www.yourwebsite/mycontroller/index 
> http://www.yourwebsite/mycontroller/index, it will display the view 
> viewName.php inside your layout layoutName.php. The view must be in 
> the directory Application/View/ControllerName and the layout in the 
> directory Application/View/Layout.
> 
> If you want a working link, put Link </mycontroller/method> inside 
> your view.
> For the moment, the Framework is only in Alpha version but soon, we 
> will add a nice documentation and a lot more feature.
> 
> I hope it will help you :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/KaiserCoder/RaveFramework/issues/2#issuecomment-95480023.
> 
> I think I'm doing something wrong.
> This is what I'm doing but is not work:

Under controller folder:
Home.php
<?php
use Rave\Core\Controller;

class Home extends Controller
{

```
 public function __construct()
 {
     $this->setLayout('default');
 }

 public function index()
 {
     $this->loadView('viewHome');
 }
```

}
?>

Under view/Home/ folder: viewHome.php

But still page not found.

I try using url mywebsite/Home or the other way but still not working.
Maybe I'm doing something wrong?

Thank you

**Comment by KaiserCoder** [comment]
In your url, home must be in lowercase : mywebsite/home
You must always call the controller name in lowercase in the url. And if you need to use '-' in the url, you can name your controller like this Controller_test and your methods like this method_name and you can call them like this : mywebsite/controller-test/method-name

If you have a view problem. Just make sure that the view file is in the directory Application/View/ControllerName

Hope I helped you :)

**Comment by KaiserCoder** [comment]
Ok, my bad, I made a mistake in a library. I corrected it. Thanks :D

**Comment by Jakub41** [comment]
Il 23/04/15 17:37, KaiserCoder ha scritto:

**Comment by Jakub41** [comment]
Hey, I have a question I'm trying to add the css and the scripts but is not working. 
I made this <link rel="stylesheet" type="text/css" href="css/main.css"> but I receive an error regarding the controller doesn't exist. I have to create a controller for see the css on my page?
Thanks

**Comment by stardisblue** [comment]
Hi, you just need to include them in your view (in html)

**Comment by Jakub41** [comment]
Il 26/04/15 11:29, stardisblue ha scritto:

**Comment by stardisblue** [comment]
Hi,
The problem is coming from the rewrite rules defined in the .htaccess.
You need to store the css/js files in a folder named public/ 
example : https://github.com/KaiserCoder/RaveCMS

**Comment by Jakub41** [comment]
Il 26/04/15 15:22, stardisblue ha scritto:
