### ISSUE TITLE
Is it a mistake or something else in the 'Memcached' file 

### ISSUE THREAD

**Issue by sfengyuan** [KaiserCoder/RaveFramework#3]
```
use \Exception;
use \Memcached;
```

I was confused,Is the  backslash necessary? Because the php manual says:"... the leading backslash is unnecessary and not allowed, as import names must be fully qualified, and are not processed relative to the current namespace."

**Comment by sfengyuan** [comment]
There is a conflict between the class name and the use \Memcached line.
And this line 

```
$resource = $this->instance()->get($key);
```

missed a parameter

**Comment by KaiserCoder** [comment]
I tried to fix it. If you need more help, check out the original repo : https://github.com/AlekseyKorzun/memcached-wrapper-php
Don't hesitate to come back if you have any trouble, we may change this library to use a custom one. :)

**Comment by sfengyuan** [comment]
Thanks for your reply，very helpful。
